apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
  labels:
    app.kubernetes.io/name: cm-pod
spec:
  containers:
  - name: cm-pod
    image: mahendrshinde/myweb:1
    envFrom:
    - configMapRef:
        name: config1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
