apiVersion: v1
kind: ConfigMap
metadata:
  name: config1
data:
  SQL_CONNECTION_STRING: "Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;"
  REDIS_CONNECTION_STRING: "redis:6379"
  API_URL: "http://api.myapp.com"
