apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
