apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  labels:
    app.kubernetes.io/name: vol-pod
spec:
  volumes:
  - name: datavol
    persistentVolumeClaim:
      claimName: claim1
  containers:
  - name: myapp
    image: mahendrshinde/myweb:1
    volumeMounts:
    - name: datavol
      mountPath: /data
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
