apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
spec:
  containers:
  - name: test
    image: nginx:alpine
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    
