apiVersion: v1
kind: Secret
metadata:
  name: secret1
data:
  SQL_CONNECTION_STRING: "U2VydmVyPW15U2VydmVyQWRkcmVzcztEYXRhYmFzZT1teURhdGFCYXNlO1VzZXIgSWQ9bXlVc2VybmFtZTtQYXNzd29yZD1teVBhc3N3b3JkOwo="
  REDIS_CONNECTION_STRING: "cmVkaXM6NjM3OQ=="
  API_URL: "aHR0cDovL2FwaS5teWFwcC5jb20="
