apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
        - name: web
          image: mahendrshinde/image-resizer
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "348Mi"  # Memory Units KI, MI, GI
              cpu: "1"         # CPU : 1000m => 1 Logical CPU 
